---
title: "Deep Dive 1: readxl::read_excel"
description: |
  A closer look at the `read_excel` from the `readr` 📦 .
author:
  - name: Vishal Katti
    url: {}
date: 2022-02-17
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Introduction

This is the first of many deep-dive blogs I intend to write over the
course of few months. I will cover some common (and not-so-common)
functions from various R and Python packages. I choose those functions
that deal with basic user actions like reading/writing files, some
common data wrangling and possibly some visualizations. Some of you may
say that there is enough documentation available online, why do we need
this? I feel that while R, and to some extent Python, does have enough
documentation, we get only code examples. Only in vignettes do we see
the code outputs but when you have functions dealing with external
files/systems, rarely do you get any views or screenshots. This is the
base thought behind this endeavor.
